---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: kubeapp
  name: kubeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - image: docker.io/kubelancer/kubewebapp:v1.0.0
        name: kubeapp
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    app: kubeapp
  name: kubeapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kubeapp
  sessionAffinity: None
  type: ClusterIP
---
